### Integration tests configuration
postgres:
  url: localhost:9999

spring:
  datasource:
    url: jdbc:postgresql://${postgres.url:localhost:9999}/vehicle_compliance
    hikari:
      maximum-pool-size: 2
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master-test.yaml

aws:
  s3:
    endpoint: http://${aws.s3.url:localhost:4572}
  sqs:
    endpoint: http://${aws.sqs.url:localhost:4576}
    reporting-data-queue-name: data_queue.fifo

redis:
  enabled: true
  endpoint: ${redis.url:localhost}
  port: ${redis.custom.port:6380}

services:
  national-taxi-register:
    root-url: http://localhost:1080
  tariff-service:
    root-url: http://localhost:1080
  payments:
    root-url: http://localhost:1080
    enabled: true
  mod:
    root-url: http://localhost:1080

dvla-api-endpoint: http://localhost:1080
dvla-authentication-endpoint: http://localhost:1080/