### Integration tests configuration

# Uncomment if microservice uses Postgres/RDS, delete otherwise
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:9999/vehicle_compliance
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

aws:
  s3:
    endpoint: http://localhost:4572

services:
  connection-timeout-seconds: 29
  read-timeout-seconds: 29
  remote-vehicle-data:
    use-remote-api: false

exemptions:
  
redis:
    enabled: false