CREATE ROLE ntr_readonly_role WITH
NOLOGIN
NOSUPERUSER
NOINHERIT
NOCREATEDB
NOCREATEROLE
NOREPLICATION;
GRANT CONNECT ON DATABASE "taxi_phv" TO ntr_readonly_role;
GRANT USAGE ON SCHEMA public TO ntr_readonly_role;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ntr_readonly_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ntr_readonly_role;
GRANT USAGE ON SCHEMA audit TO ntr_readonly_role;
GRANT SELECT ON ALL TABLES IN SCHEMA audit TO ntr_readonly_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT ON TABLES TO ntr_readonly_role;

CREATE ROLE ntr_readwrite_role WITH
NOLOGIN
NOSUPERUSER
NOINHERIT
NOCREATEDB
NOCREATEROLE
NOREPLICATION;
GRANT CONNECT ON DATABASE "taxi_phv" TO ntr_readwrite_role;
GRANT USAGE ON SCHEMA public TO ntr_readwrite_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ntr_readwrite_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ntr_readwrite_role;
GRANT USAGE ON SCHEMA audit TO ntr_readwrite_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA audit TO ntr_readwrite_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ntr_readwrite_role;