application:
  title: Test Lambda

management:
  endpoints:
    web:
      base-path:
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false

springfox:
  documentation:
    swagger:
      v2:
        path: /v1/swagger-docs