AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test Lambda API

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL
Resources:
  TestLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: uk.gov.caz.testlambda.amazonaws.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/test-lambda-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 1512
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: default
Outputs:
  SpringBootTestLambdaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    Export:
      Name: SpringBootTestLambdaApi
