### Integration tests configuration

# Uncomment if microservice uses Postgres/RDS, delete otherwise
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:9999/accounts
aws:
  s3:
    endpoint: http://localhost:4572
