# This profile is used when running Localstack - simulated, Docker mocked AWS environment.
# Postgres is expected to be running on localhost and can come from Docker or local installation.
# Running 'make localstack-run' sets Spring profile to 'localstack' and runs Spring-Boot app normally.
# Application can be tested as normal Spring-Boot with REST endpoints.
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi_phv
aws:
  s3:
    endpoint: http://localhost:4572
    payload-retention-bucket: apibucket
  sqs:
    endpoint: http://localhost:4576
  sns:
    endpoint: http://localhost:4575
  ses:
    senderEmail: dummy@email.gov
    endpoint: http://localhost:4579

redis:
  endpoint: localhost
  port: 6379
  enabled: false