version: '3.3'

services:
  postgres-vcc:
    build: ./postgres-with-pgaudit
    image: postgres-pgaudit-local:1
    container_name: postgres-vcc.docker
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vehicle_compliance

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin.docker
    environment:
      PGADMIN_DEFAULT_EMAIL: test@caz.com
      PGADMIN_DEFAULT_PASSWORD: pass
    network_mode: host

  sonarqube:
    image: sonarqube
    container_name: sonarqube.docker
    ports:
      - 9000:9000

  redis:
    image: grokzen/redis-cluster
    container_name: redis.docker
    ports:
      - "7000-7009:7000-7009" 