databaseChangeLog:
  - changeSet:
      id: 0024-1.0
      author: informed
      changes:
        - sql:
            comment: Update fuel types for test data.
            dbms: postgresql
            endDelimiter: ;
            splitStatements: true
            sql: -- Update Euro status values

              UPDATE vehicle
              SET eurostatus = regexp_replace(eurostatus, '(.*) (.*)', 'EURO \2');
